# output: console or pi: console will mock missing pi hardware and output image to terminal
output: pi
ledMatrix:
  rows: 16
  columns: 32
  brightness: 70
  chainedDisplays: 1
  parallelDisplays: 2
  hardwareMapping: adafruit-hat-pwm
  frameRate: 24
scenes: 
  - layers:
    - type: Fireworks
      rate: 1
      colors:
        - "#0000ff"
        - "#ffffff"
        - "#ff0000"
    - type: DailyObservances
      text: "There are no daily observances today. What's up with that?!"
      fillStyle: "#ffffff"
      size: 16
      font: Pixel Operator
      speed: 1
  - layers:
    - type: Glitter
      rate: 20
      color: "#ffad33"
      backgroundColor: "#120a00"
    - type: ScrollingText
      text: "This day in history: At least one thing interesting happened. Stay tuned for a future epic historical update."
      fillStyle: "#ffd699"
      size: 16
      font: Rainy Hearts
      speed: 1
  - layers:
    - type: Glitter
      rate: 5
      color: "#ffffff"
      backgroundColor: "#000029"
    - type: ScrollingText
      text: "Have a very productive day."
      fillStyle: "#a8a8ff"
      size: 16
      font: Pixellari
      speed: 1