# output: console or pi: console will mock missing pi hardware and output image to terminal
output: pi
ledMatrix:
  rows: 16
  columns: 32
  brightness: 70
  chainedDisplays: 1
  parallelDisplays: 2
  hardwareMapping: adafruit-hat-pwm
  frameRate: 24
scenes: 
  - layers:
    - type: Fill
      color: "#000000"
      seconds: 1
  - layers:
    - type: Fireworks
      rate: 1
    - type: DailyObservances
      text: "There are no daily observances today. What's up with that?!"
      fillStyle: "#ffffff"
      size: 16
      font: Pixel Operator
      speed: 1
  - layers:
    - type: Glitter
      rate: 20
      color: "#ffad33"
      backgroundColor: "#120a00"
    - type: ScrollingText
      text: "This day in history: Something of great significance happened."
      fillStyle: "#ffd699"
      size: 16
      font: Rainy Hearts
      speed: 1
  - layers:
    - type: Fill
      color: "#000000"
    - type: ScrollingText
      text: "All connected systems are online. For security purposes, there are 0 connected systems."
      fillStyle: "#66ff66"
      size: 16
      font: Pixel Operator
      speed: 1
  - layers:
    - type: Glitter
      rate: 5
      color: "#ffffff"
      backgroundColor: "#000029"
    - type: ScrollingText
      text: "Have a very productive day."
      fillStyle: "#a8a8ff"
      size: 16
      font: Pixellari
      speed: 1