# env: local or pi: local will mock missing pi hardware and output image to terminal
env: local
ledMatrix:
  rows: 16
  columns: 32
  brightness: 50
  chainedDisplays: 1
  parallelDisplays: 1
  hardwareMapping: adafruit-hat-pwm
  frameRate: 25
layerPlugins:
  - Color
  - Rainbow
  - RandomBlinkingDots
  - Warp2D
  - StillText
  - ScrollingText
scenes: 
  - layers:
    - type: Fill
      fillStyle: "#3e046f"
    - type: ScrollingText
      text: "Happy Easter Awesome People!"
      fillStyle: "#ffffff"
      size: 16
      font: Pixellari
      speed: 1
    transitionIn:
      type: fade
      milliseconds: 1000
    transitionOut:
      type: fade
      milliseconds: 1000
  - layers:
    - type: RandomBlinkingDots
      milliseconds: 30000
  - layers:
    - type: Warp2D
      backgroundHex: #023ca6
      starHex: #ffffff
    - type: TextStill
      text: "Go!"
      delaymilliseconds: 2000
      milliseconds: 3000
    - type: TextStill
      text: "Far!"
      delaymilliseconds: 1000
      milliseconds: 5000
    transitionIn:
      type: fade
      milliseconds: 2000
    transitionOut:
      type: fade
      milliseconds: 1000
