# output: console or pi: console will mock missing pi hardware and output image to terminal
output: pi
ledMatrix:
    rows: 16
    columns: 32
    brightness: 100
    chainedDisplays: 1
    parallelDisplays: 4
    hardwareMapping: adafruit-hat-pwm
    frameRate: 35
scenes:
    - layers:
          - type: Lightning
            seconds: 200
